/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error": "#ffb4ab",
        "on-primary-container": "#395283",
        "primary-container": "#aec6ff",
        "surface-bright": "#38393d",
        "surface-container-highest": "#343538",
        "outline-variant": "#44474f",
        "on-primary": "#132f5f",
        "on-surface-variant": "#c4c6d0",
        "on-error": "#690005",
        "inverse-surface": "#e3e2e6",
        "secondary-container": "#474746",
        "on-secondary-fixed": "#1b1c1b",
        "primary-accent": "#0070f3",
        "background": "#000000",
        "surface-container": "#1e1f23",
        "primary-fixed-dim": "#aec6ff",
        "on-primary-fixed": "#001a42",
        "surface": "#121317",
        "tertiary-fixed": "#ffdbcd",
        "surface-container-high": "#292a2d",
        "on-tertiary-fixed-variant": "#6c3922",
        "on-secondary-fixed-variant": "#474746",
        "secondary-fixed-dim": "#c8c6c5",
        "on-error-container": "#ffdad6",
        "inverse-on-surface": "#2f3034",
        "surface-dim": "#121317",
        "surface-container-lowest": "#0d0e11",
        "on-tertiary-fixed": "#360f00",
        "on-primary-fixed-variant": "#2d4677",
        "tertiary-container": "#ffb596",
        "on-tertiary": "#51230e",
        "on-secondary": "#303030",
        "on-tertiary-container": "#7a442c",
        "surface-tint": "#aec6ff",
        "on-secondary-container": "#b6b5b4",
        "primary": "#d8e2ff",
        "secondary": "#c8c6c5",
        "on-surface": "#e3e2e6",
        "secondary-fixed": "#e4e2e1",
        "surface-variant": "#343538",
        "on-background": "#e3e2e6",
        "outline": "#333333",
        "primary-fixed": "#d8e2ff",
        "surface-container-low": "#1a1b1f",
        "error-container": "#93000a",
        "tertiary": "#ffdbcd",
        "inverse-primary": "#465e90",
        "tertiary-fixed-dim": "#ffb597"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "lg": "40px",
        "xl": "64px",
        "margin": "24px",
        "gutter": "16px",
        "sm": "12px",
        "xs": "8px",
        "base": "4px",
        "md": "24px"
      },
      fontFamily: {
        "headline-lg": ["Geist", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "body-lg": ["Geist", "sans-serif"],
        "display": ["Geist", "sans-serif"],
        "caption": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-mono": ["13px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "display": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "600" }],
        "caption": ["12px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
}
